[service]
AppMode = debug
HttpPort = :3000

[mysql]
DB = mysql
DbHost = localhost
DbPort = 3306
DbUser = root
DbPassword = sunmengfei123...
DbName = gin_mall

[redis]
RedisDb = redis
RedisAddr = 127.0.0.1:6379
RedisPw =
RedisDbName = 2

[qiniu]
AccessKey =
SecretKey =
Bucket =
QiniuServer =  ;七牛云的域名

[email]
ValidEmail = http://localhost:8080/#/vaild/email/
SmtpHost = smtp.qq.com
SmtpEmail =
SmtpPass =

[path]
Host = http://127.0.0.1
; 产品图片
ProductPath =  /static/imgs/product/
; 用户头像图片
AvatarPath = /static/imgs/avatar/